// flow-typed signature: 6829f5f92d4947f6a2f32873a02aefef
// flow-typed version: <<STUB>>/react-native-mobx_v^0.3.1/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-mobx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-mobx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-mobx/index' {
  declare module.exports: $Exports<'react-native-mobx'>;
}
declare module 'react-native-mobx/index.js' {
  declare module.exports: $Exports<'react-native-mobx'>;
}
